n = input('Digite algo: ')
print ('O tipo primitivo de n é ', type(n))
print ('Só tem espaços? ', n.isspace())
print ('É um número? ', n.isnumeric())
print ('É alfabético? ', n.isalpha())
print ('É alfanumérico? ', n.isalnum())
print ('Está minúscula? ', n.islower())
print ('Está maiúscula? ', n.isupper())
print ('Está capitalizada? ', n.istitle())